# Copyright 2018 Bitwise IO, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

[package]
name = "sawtooth-pbft"
version = "0.1.0"
authors = ["Bitwise IO, Inc"]

[dependencies]
sawtooth_sdk = { git = "https://github.com/aludvik/sawtooth-core.git", branch = "raft-prototype-demo" }
simple_logger = "0.5.0"
protobuf = "2"
clap = "2.31"
log = "0.4"
log4rs = "0.8"


[build-dependencies]
protoc-rust = "2"
